version: "3"
services:
  api:
    build: ..
    environment:
      ROOT_PATH: "/test"
    ports:
      - "5001:5001"
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - "./nginx-config:/etc/nginx/conf.d/default.conf"
